---
- hosts: all

  vars:
    java_version: "7u95-*"
    elasticsearch_cluster_name: "logstash"
    kibana_bind_host: "0.0.0.0"

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "azavea.elasticsearch" }
    - { role: "azavea.logstash" }
    - { role: "azavea.kibana" }

  tasks:
    - name: Add Logstash user to service group
      user: name=logstash
            append=yes
            groups=adm
            state=present

    - name: Configure Logstash
      template: src=templates/logstash.conf.j2 dest=/etc/logstash/conf.d/logstash.conf
      notify:
        - Restart Logstash
